// =====================================================
//  VERTALINGEN – alle teksten van de app, per taal
// =====================================================

const teksten = {
  nl: {
    tabNieuw: "Account maken",
    tabLogin: "Inloggen",
    wachtwoord: "Wachtwoord",
    wachtwoordNieuw: "Wachtwoord (min. 8 tekens)",
    vergeten: "Wachtwoord vergeten?",
    nieuwWachtwoordTitel: "Kies een nieuw wachtwoord",
    bewaarWachtwoord: "Bewaar wachtwoord",
    bevestigMail: "Bijna klaar! We stuurden je één mail om je e-mailadres te bevestigen. Daarna log je gewoon in met je wachtwoord.",
    resetVerstuurd: "Check je mailbox: we stuurden je een link om een nieuw wachtwoord te kiezen.",
    eerstEmail: "Vul eerst je e-mailadres in.",
    foutGegevens: "E-mailadres of wachtwoord klopt niet.",
    foutBevestigen: "Bevestig eerst je e-mailadres via de mail die we je stuurden.",
    foutBestaat: "Er bestaat al een account met dit e-mailadres. Log in, of kies 'Wachtwoord vergeten?'.",
    foutWachtwoord: "Kies een wachtwoord van minstens 8 tekens.",
    ondertitel: "Koffiebars en wielercafés in Vlaanderen en Brussel",
    kleur: "Kleur:",
    alleLanden: "Alle landen",
    kenmerk_laptop: "PC-friendly",
    kenmerk_wifi: "Gratis wifi",
    kenmerk_stopcontact: "Stopcontacten",
    kenmerk_rustig: "Rustig",
    kenmerkenBewerken: "✏️ Aanpassen",
    dichtbij: "📍 Dichtbij mij",
    locatieZoeken: "📍 Locatie zoeken…",
    geenLocatie: "Je browser kan je locatie niet bepalen.",
    locatieGeweigerd: "Je locatie kon niet bepaald worden. Sta locatietoegang toe voor deze site in je browserinstellingen.",
    jijBentHier: "Jij bent hier",
    morgen: "morgen",
    dag_ma: "ma",
    dag_di: "di",
    dag_wo: "wo",
    dag_do: "do",
    dag_vr: "vr",
    dag_za: "za",
    dag_zo: "zo",
    nuOpen: "Nu open",
    tot: "tot",
    gesloten: "Gesloten",
    opent: "opent",
    openingsuren: "Openingsuren",
    urenUitleg: "Bv. 08:00-17:00, of 08:00-12:00, 13:00-18:00. Leeg = gesloten. Alles leeg = onbekend.",
    bewaarUren: "Bewaar uren",
    zondagVroeg: "Zondag vroeg",
    reviewGeven: "Review geven",
    anoniem: "Anoniem",
    reviewTekst: "Wat vond je ervan? (optioneel)",
    reviewAanpassen: "Review aanpassen",
    reviewPlaatsen: "Review plaatsen",
    reviewVerwijderen: "Verwijderen",
    nogGeenReviews: "Nog geen reviews. Wees de eerste!",
    kiesSterren: "Kies eerst een aantal sterren.",
    zekerReview: "Deze review verwijderen?",
    barVoorstellen: "➕ Bar voorstellen",
    voorstelNaam: "Naam van de bar",
    voorstelWaarom: "Waarom is ze de moeite? (optioneel)",
    voorstelSturen: "Voorstel sturen",
    voorstelBedankt: "Bedankt! We bekijken je voorstel zo snel mogelijk.",
    voorstellen: "Voorstellen",
    geenVoorstellen: "Geen nieuwe voorstellen.",
    overnemen: "Overnemen",
    weigeren: "Weigeren",
    zekerWeigeren: "Dit voorstel weigeren en verwijderen?",
    accountVerwijderen: "Account verwijderen",
    zekerAccount: "Weet je het zeker? Je account, je favorieten en je reviews worden definitief verwijderd.",
    accountVerwijderd: "Je account is verwijderd. Bedankt dat je Roast Route gebruikte!",
    privacyLink: "Privacyverklaring",
    alles: "Alles",
    vlaanderen: "Vlaanderen",
    antwerpen: "Antwerpen",
    gent: "Gent",
    brussel: "Brussel",
    email: "jouw@email.be",
    inloggen: "Inloggen",
    uitloggen: "Uitloggen",
    checkMail: "Check je mailbox en klik op de link om in te loggen.",
    loginMislukt: "Inloggen lukte niet:",
    privacy: "We bewaren alleen je voornaam, je e-mailadres, je favorieten, je bewaarde routes, je nieuwsbriefkeuze en (als je het invult) waarvoor je de app gebruikt. Je kunt je altijd uitschrijven.",
    welkomTitel: "Welkom bij Roast Route",
    welkomTekst: "Ontdek de beste koffiebars, bewaar je favorieten en mis geen enkele nieuwe bar.",
    voornaam: "Voornaam",
    nieuwsbriefVraag: "Ja, stuur me maandelijks een mail met nieuwe bars.",
    nieuwsbriefKort: "Maandelijkse mail",
    accountMaken: "Account maken",
    zonderAccount: "Eerst even rondkijken",
    adres: "Straat nr, gemeente",
    opslaanMislukt: "Opslaan lukte niet:",
    zekerVerwijderen: "Zeker verwijderen?",
    foto: "📷 Foto",
    fotoKiezen: "Foto (optioneel)",
    fotoBezig: "Foto uploaden…",
    zoek: "Zoek een stop…",
    alleTypes: "Alle types",
    koffie: "Specialty koffie",
    wieler: "Wielercafé",
    favorieten: "★ Mijn favorieten",
    nieuweStop: "Nieuwe stop",
    naam: "Naam",
    beschrijving: "Korte beschrijving",
    wielervriendelijk: "Wielervriendelijk",
    kiesPlek: "Vul een adres in en klik op 📍, of klik op de kaart.",
    plekGekozen: "Plek gekozen ✓",
    eerstKlikken: "Zoek eerst het adres op, of klik op de kaart!",
    toevoegen: "Toevoegen",
    stops: "stops",
    // Route plannen
    routePlannen: "🚴 Route plannen",
    jouwRoute: "Jouw route",
    routeUitleg: "Klik op de kaart om punten toe te voegen, en op een bar (of ➕ in de lijst) om ze mee te nemen. Of laad je eigen GPX in.",
    rondrit: "Rondrit: terug naar de start",
    startHier: "📍 Start bij mij",
    gpx: "⬇️ GPX",
    googleMaps: "Google Maps",
    routeWissen: "Route wissen",
    inRoute: "In route",
    naarRoute: "In route",
    routeBerekenen: "Route berekenen…",
    routeMislukt: "De route kon niet berekend worden. Probeer het straks opnieuw.",
    routeStart: "Start",
    routePunt: "Punt",
    aan: "aan",
    barsLangsRoute: "Koffiebars met max. 2 km omweg",
    geenBarsLangsRoute: "Geen bars met minder dan 2 km omweg.",
    opDeRoute: "op je route",
    omweg: "omweg",
    mijnLocatie: "Mijn locatie",
    stijl_snel: "Snel",
    stijl_fietspaden: "Fietspaden",
    stijl_rustig: "Weinig verkeer",
    routeReserve: "Eenvoudige route: de fietsrouteplanner is even niet bereikbaar.",
    gebruikVraag: "Waarvoor gebruik je Roast Route? (optioneel)",
    gebruik_koersen: "🚴 Koersen",
    gebruik_ontspannen: "☕ Ontspannen",
    gebruik_werken: "💻 Werken",
    routeDelen: "🔗 Delen",
    routeBewaren: "💾 Bewaren",
    deelTekst: "Rij je mee? Dit is mijn route langs de beste koffiestops ☕🚴",
    linkGekopieerd: "Link gekopieerd! Plak hem in WhatsApp, Messenger, …",
    kopieerLink: "Kopieer deze link:",
    eerstInloggen: "Log in om routes te bewaren.",
    routeStandaardNaam: "Rit van",
    routeNaamVraag: "Hoe wil je deze route noemen?",
    routeBewaard: "Route bewaard ✓",
    mijnRoutes: "Mijn routes",
    routeOpenen: "Openen",
    zekerRouteWissen: "Deze route verwijderen?",
    gpxImporteren: "📂 Eigen GPX inladen",
    ongedaanMaken: "↶ Ongedaan maken",
    optimaliseren: "🔀 Volgorde optimaliseren",
    importKlik: "Je werkt met een ingeladen GPX. Klik op een bar om ze toe te voegen, of wis de route om zelf te plannen.",
    gpxFout: "Dit GPX-bestand kan ik niet lezen. Exporteer je route opnieuw als GPX (niet als FIT of TCX).",
    routeVervangen: "Je huidige route vervangen door deze GPX?",
    omwegBerekenen: "Omweg berekenen…",
    importDelenUitleg: "Een ingeladen GPX kan je bewaren en downloaden, maar niet via een link delen.",
    publiekeRoutes: "Routes van Roast Route",
    publicerenUitleg: "Publiceren: iedereen ziet deze route",
    // Mijn profiel
    statistieken: "Statistieken",
    profielfoto: "Profielfoto",
    profielfotoUitleg: "Je foto staat bij je naam en bij je reviews.",
    fotoKiezenProfiel: "📷 Foto kiezen",
    fotoVerwijderen: "Foto verwijderen",
    mijnGegevens: "Mijn gegevens",
    voornaamLabel: "Voornaam",
    taalLabel: "Taal",
    bewaren: "Bewaren",
    voorkeuren: "Voorkeuren",
    voorkeurenUitleg: "De app past zich hieraan aan: je favoriete regio staat klaar bij het openen, en routes passen bij jouw fiets.",
    gebruikVraagKort: "Waarvoor gebruik je Roast Route?",
    favorieteRegio: "Favoriete regio",
    fietsType: "Mijn fiets",
    geenKeuze: "—",
    fiets_koersfiets: "Koersfiets",
    fiets_gravel: "Gravelbike",
    fiets_stadsfiets: "Stadsfiets",
    fiets_ebike: "E-bike",
    snelheidLabel: "Gemiddelde snelheid (km/u)",
    wachtwoordWijzigen: "Wachtwoord wijzigen",
    wachtwoordWijzigenKnop: "Wachtwoord wijzigen",
    wachtwoordGewijzigd: "Je wachtwoord is gewijzigd ✓",
    geenNaam: "Mijn profiel",
    lidSinds: "lid sinds",
    statFavorieten: "favorieten",
    statReviews: "reviews",
    statRoutes: "routes",
    statKm: "km aan routes",
    profielBewaard: "Bewaard ✓",
    startTitel: "Maak je profiel af",
    startTekst: "Nog even dit, zodat Roast Route meteen bij jou past. Alles is optioneel.",
    startKlaar: "Klaar",
    overslaan: "Overslaan",
    // Bars importeren (beheerder)
    importTitel: "📥 Bars importeren",
    importUitleg: "Kies een lijst (.json of .csv). De app zoekt elk adres op de kaart; jij kijkt na en voegt toe.",
    importKiezen: "📂 Lijst kiezen",
    importFout: "Deze lijst kan ik niet lezen. Gebruik een .json- of .csv-bestand met minstens naam en adres.",
    importZoeken: "Adressen opzoeken…",
    importKlaar: "Klaar met zoeken: {n} bars staan klaar. Kijk ze na en klik op Toevoegen.",
    importToevoegen: "➕ {n} bars toevoegen",
    importToevoegenBezig: "Toevoegen…",
    importToegevoegd: "{n} bars toegevoegd aan de kaart ✓",
    importNietZeker: "niet zeker of ze nog open is",
    importStatus_wachten: "wacht",
    importStatus_zoeken: "zoeken…",
    importStatus_gevonden: "gevonden",
    importStatus_nietGevonden: "adres niet gevonden",
    importStatus_bestaat: "staat al op de kaart",
    importStatus_anderLand: "gevonden in een ander land, kijk na",
    importStatus_toegevoegd: "toegevoegd",
    importStatus_fout: "toevoegen mislukt",
    badge_eersteReview: "Eerste review",
    badge_recensent: "Recensent",
    badge_verzamelaar: "Verzamelaar",
    badge_planner: "Routeplanner",
    badge_centurion: "Centurion",
    badge_ontdekker: "Ontdekker",
    badgeUitleg_eersteReview: "Schrijf je eerste review",
    badgeUitleg_recensent: "Schrijf 5 reviews",
    badgeUitleg_verzamelaar: "Bewaar 10 favoriete bars",
    badgeUitleg_planner: "Bewaar je eerste route",
    badgeUitleg_centurion: "Bewaar een route van 100 km of meer",
    badgeUitleg_ontdekker: "Favorieten of reviews in 3 verschillende regio's",
    route: "Route ↗",
    verwijder: "🗑️ Verwijder",
    fout: "Kon stops.json niet laden. Start je de app via de lokale server?",
    zoekOpKaart: "📍 Zoek op kaart",
    plaats: "Gemeente",
    land: "Land",
    eerstAdres: "Vul eerst een adres in.",
    adresZoeken: "Adres zoeken…",
    adresGevonden: "Gevonden! Staat de speld niet helemaal juist? Versleep ze.",
    adresNietGevonden: "Adres niet gevonden. Probeer met straat, nummer en gemeente, of klik op de kaart.",
  },

  fr: {
    tabNieuw: "Créer un compte",
    tabLogin: "Se connecter",
    wachtwoord: "Mot de passe",
    wachtwoordNieuw: "Mot de passe (min. 8 caractères)",
    vergeten: "Mot de passe oublié ?",
    nieuwWachtwoordTitel: "Choisis un nouveau mot de passe",
    bewaarWachtwoord: "Enregistrer le mot de passe",
    bevestigMail: "Presque fini ! Nous t'avons envoyé un e-mail pour confirmer ton adresse. Ensuite, connecte-toi simplement avec ton mot de passe.",
    resetVerstuurd: "Vérifie ta boîte mail : nous t'avons envoyé un lien pour choisir un nouveau mot de passe.",
    eerstEmail: "Remplis d'abord ton adresse e-mail.",
    foutGegevens: "Adresse e-mail ou mot de passe incorrect.",
    foutBevestigen: "Confirme d'abord ton adresse via l'e-mail que nous t'avons envoyé.",
    foutBestaat: "Un compte existe déjà avec cette adresse. Connecte-toi ou choisis « Mot de passe oublié ? ».",
    foutWachtwoord: "Choisis un mot de passe d'au moins 8 caractères.",
    ondertitel: "Bars à café et cafés cyclistes en Flandre et à Bruxelles",
    kleur: "Couleur :",
    alleLanden: "Tous les pays",
    kenmerk_laptop: "PC bienvenu",
    kenmerk_wifi: "Wifi gratuit",
    kenmerk_stopcontact: "Prises",
    kenmerk_rustig: "Calme",
    kenmerkenBewerken: "✏️ Modifier",
    dichtbij: "📍 Près de moi",
    locatieZoeken: "📍 Recherche de la position…",
    geenLocatie: "Ton navigateur ne peut pas déterminer ta position.",
    locatieGeweigerd: "Impossible de déterminer ta position. Autorise l'accès à la localisation pour ce site dans les réglages du navigateur.",
    jijBentHier: "Tu es ici",
    morgen: "demain",
    dag_ma: "lun",
    dag_di: "mar",
    dag_wo: "mer",
    dag_do: "jeu",
    dag_vr: "ven",
    dag_za: "sam",
    dag_zo: "dim",
    nuOpen: "Ouvert",
    tot: "jusqu'à",
    gesloten: "Fermé",
    opent: "ouvre",
    openingsuren: "Heures d'ouverture",
    urenUitleg: "Ex. 08:00-17:00, ou 08:00-12:00, 13:00-18:00. Vide = fermé. Tout vide = inconnu.",
    bewaarUren: "Enregistrer les heures",
    zondagVroeg: "Dimanche tôt",
    reviewGeven: "Donner un avis",
    anoniem: "Anonyme",
    reviewTekst: "Qu'en as-tu pensé ? (facultatif)",
    reviewAanpassen: "Modifier l'avis",
    reviewPlaatsen: "Publier l'avis",
    reviewVerwijderen: "Supprimer",
    nogGeenReviews: "Pas encore d'avis. Sois le premier !",
    kiesSterren: "Choisis d'abord un nombre d'étoiles.",
    zekerReview: "Supprimer cet avis ?",
    barVoorstellen: "➕ Proposer un bar",
    voorstelNaam: "Nom du bar",
    voorstelWaarom: "Pourquoi vaut-il le détour ? (facultatif)",
    voorstelSturen: "Envoyer la proposition",
    voorstelBedankt: "Merci ! Nous examinerons ta proposition au plus vite.",
    voorstellen: "Propositions",
    geenVoorstellen: "Aucune nouvelle proposition.",
    overnemen: "Reprendre",
    weigeren: "Refuser",
    zekerWeigeren: "Refuser et supprimer cette proposition ?",
    accountVerwijderen: "Supprimer le compte",
    zekerAccount: "Tu es sûr ? Ton compte, tes favoris et tes avis seront définitivement supprimés.",
    accountVerwijderd: "Ton compte a été supprimé. Merci d'avoir utilisé Roast Route !",
    privacyLink: "Politique de confidentialité",
    alles: "Tout",
    vlaanderen: "Flandre",
    antwerpen: "Anvers",
    gent: "Gand",
    brussel: "Bruxelles",
    email: "ton@email.be",
    inloggen: "Se connecter",
    uitloggen: "Se déconnecter",
    checkMail: "Vérifie ta boîte mail et clique sur le lien pour te connecter.",
    loginMislukt: "Connexion impossible :",
    privacy: "Nous gardons uniquement ton prénom, ton adresse e-mail, tes favoris, tes parcours enregistrés, ton choix de newsletter et (si tu le remplis) l'usage que tu fais de l'app. Tu peux te désinscrire à tout moment.",
    welkomTitel: "Bienvenue sur Roast Route",
    welkomTekst: "Découvre les meilleurs arrêts café, garde tes favoris et ne rate aucun nouveau bar.",
    voornaam: "Prénom",
    nieuwsbriefVraag: "Oui, envoie-moi chaque mois un e-mail avec les nouveaux bars.",
    nieuwsbriefKort: "E-mail mensuel",
    accountMaken: "Créer un compte",
    zonderAccount: "D'abord jeter un œil",
    adres: "Rue n°, commune",
    opslaanMislukt: "Enregistrement impossible :",
    zekerVerwijderen: "Vraiment supprimer ?",
    foto: "📷 Photo",
    fotoKiezen: "Photo (facultatif)",
    fotoBezig: "Envoi de la photo…",
    zoek: "Chercher un arrêt…",
    alleTypes: "Tous les types",
    koffie: "Café de spécialité",
    wieler: "Café cycliste",
    favorieten: "★ Mes favoris",
    nieuweStop: "Nouvel arrêt",
    naam: "Nom",
    beschrijving: "Courte description",
    wielervriendelijk: "Adapté aux cyclistes",
    kiesPlek: "Entre une adresse et clique sur 📍, ou clique sur la carte.",
    plekGekozen: "Endroit choisi ✓",
    eerstKlikken: "Cherche d'abord l'adresse, ou clique sur la carte !",
    toevoegen: "Ajouter",
    stops: "arrêts",
    // Route plannen
    routePlannen: "🚴 Planifier un parcours",
    jouwRoute: "Ton parcours",
    routeUitleg: "Clique sur la carte pour ajouter des points, et sur un bar (ou ➕ dans la liste) pour l'inclure. Ou importe ton propre GPX.",
    rondrit: "Boucle : retour au départ",
    startHier: "📍 Partir d'ici",
    gpx: "⬇️ GPX",
    googleMaps: "Google Maps",
    routeWissen: "Effacer le parcours",
    inRoute: "Dans le parcours",
    naarRoute: "Au parcours",
    routeBerekenen: "Calcul du parcours…",
    routeMislukt: "Impossible de calculer le parcours. Réessaie plus tard.",
    routeStart: "Départ",
    routePunt: "Point",
    aan: "à",
    barsLangsRoute: "Cafés à 2 km de détour max.",
    geenBarsLangsRoute: "Aucun café à moins de 2 km de détour.",
    opDeRoute: "sur ton parcours",
    omweg: "de détour",
    mijnLocatie: "Ma position",
    stijl_snel: "Rapide",
    stijl_fietspaden: "Pistes cyclables",
    stijl_rustig: "Peu de trafic",
    routeReserve: "Parcours simple : le planificateur vélo est momentanément indisponible.",
    gebruikVraag: "Pourquoi utilises-tu Roast Route ? (facultatif)",
    gebruik_koersen: "🚴 Vélo",
    gebruik_ontspannen: "☕ Détente",
    gebruik_werken: "💻 Travail",
    routeDelen: "🔗 Partager",
    routeBewaren: "💾 Enregistrer",
    deelTekst: "Tu viens rouler ? Voici mon parcours par les meilleurs cafés ☕🚴",
    linkGekopieerd: "Lien copié ! Colle-le dans WhatsApp, Messenger, …",
    kopieerLink: "Copie ce lien :",
    eerstInloggen: "Connecte-toi pour enregistrer des parcours.",
    routeStandaardNaam: "Sortie de",
    routeNaamVraag: "Quel nom pour ce parcours ?",
    routeBewaard: "Parcours enregistré ✓",
    mijnRoutes: "Mes parcours",
    routeOpenen: "Ouvrir",
    zekerRouteWissen: "Supprimer ce parcours ?",
    gpxImporteren: "📂 Importer mon GPX",
    ongedaanMaken: "↶ Annuler",
    optimaliseren: "🔀 Optimiser l'ordre",
    importKlik: "Tu utilises un GPX importé. Clique sur un café pour l'ajouter, ou efface le parcours pour planifier toi-même.",
    gpxFout: "Je ne peux pas lire ce fichier GPX. Exporte ton parcours à nouveau en GPX (pas en FIT ou TCX).",
    routeVervangen: "Remplacer ton parcours actuel par ce GPX ?",
    omwegBerekenen: "Calcul du détour…",
    importDelenUitleg: "Un GPX importé peut être enregistré et téléchargé, mais pas partagé par lien.",
    publiekeRoutes: "Parcours de Roast Route",
    publicerenUitleg: "Publier : tout le monde voit ce parcours",
    // Mijn profiel
    statistieken: "Statistiques",
    profielfoto: "Photo de profil",
    profielfotoUitleg: "Ta photo apparaît à côté de ton nom et de tes avis.",
    fotoKiezenProfiel: "📷 Choisir une photo",
    fotoVerwijderen: "Supprimer la photo",
    mijnGegevens: "Mes données",
    voornaamLabel: "Prénom",
    taalLabel: "Langue",
    bewaren: "Enregistrer",
    voorkeuren: "Préférences",
    voorkeurenUitleg: "L'app s'adapte : ta région préférée s'affiche à l'ouverture, et les parcours s'adaptent à ton vélo.",
    gebruikVraagKort: "Pourquoi utilises-tu Roast Route ?",
    favorieteRegio: "Région préférée",
    fietsType: "Mon vélo",
    geenKeuze: "—",
    fiets_koersfiets: "Vélo de route",
    fiets_gravel: "Gravel",
    fiets_stadsfiets: "Vélo de ville",
    fiets_ebike: "Vélo électrique",
    snelheidLabel: "Vitesse moyenne (km/h)",
    wachtwoordWijzigen: "Changer le mot de passe",
    wachtwoordWijzigenKnop: "Changer le mot de passe",
    wachtwoordGewijzigd: "Ton mot de passe a été changé ✓",
    geenNaam: "Mon profil",
    lidSinds: "membre depuis",
    statFavorieten: "favoris",
    statReviews: "avis",
    statRoutes: "parcours",
    statKm: "km de parcours",
    profielBewaard: "Enregistré ✓",
    startTitel: "Complète ton profil",
    startTekst: "Encore ceci, pour que Roast Route te corresponde tout de suite. Tout est facultatif.",
    startKlaar: "C'est parti",
    overslaan: "Passer",
    badge_eersteReview: "Premier avis",
    badge_recensent: "Critique",
    badge_verzamelaar: "Collectionneur",
    badge_planner: "Planificateur",
    badge_centurion: "Centurion",
    badge_ontdekker: "Explorateur",
    badgeUitleg_eersteReview: "Écris ton premier avis",
    badgeUitleg_recensent: "Écris 5 avis",
    badgeUitleg_verzamelaar: "Garde 10 cafés en favoris",
    badgeUitleg_planner: "Enregistre ton premier parcours",
    badgeUitleg_centurion: "Enregistre un parcours de 100 km ou plus",
    badgeUitleg_ontdekker: "Favoris ou avis dans 3 régions différentes",
    route: "Itinéraire ↗",
    verwijder: "🗑️ Supprimer",
    fout: "Impossible de charger stops.json. L'app tourne-t-elle via le serveur local ?",
    zoekOpKaart: "📍 Chercher sur la carte",
    plaats: "Commune",
    land: "Pays",
    eerstAdres: "Entre d'abord une adresse.",
    adresZoeken: "Recherche de l'adresse…",
    adresGevonden: "Trouvé ! L'épingle n'est pas tout à fait au bon endroit ? Déplace-la.",
    adresNietGevonden: "Adresse introuvable. Essaie avec rue, numéro et commune, ou clique sur la carte.",
  },

  en: {
    tabNieuw: "Create account",
    tabLogin: "Log in",
    wachtwoord: "Password",
    wachtwoordNieuw: "Password (min. 8 characters)",
    vergeten: "Forgot your password?",
    nieuwWachtwoordTitel: "Choose a new password",
    bewaarWachtwoord: "Save password",
    bevestigMail: "Almost there! We sent you one email to confirm your address. After that, just log in with your password.",
    resetVerstuurd: "Check your inbox: we sent you a link to choose a new password.",
    eerstEmail: "Fill in your email address first.",
    foutGegevens: "Email address or password is incorrect.",
    foutBevestigen: "Please confirm your email address first, using the email we sent you.",
    foutBestaat: "An account with this email already exists. Log in, or choose 'Forgot your password?'.",
    foutWachtwoord: "Choose a password of at least 8 characters.",
    ondertitel: "Coffee bars and cycling cafés in Flanders and Brussels",
    kleur: "Colour:",
    alleLanden: "All countries",
    kenmerk_laptop: "PC-friendly",
    kenmerk_wifi: "Free wifi",
    kenmerk_stopcontact: "Power outlets",
    kenmerk_rustig: "Quiet",
    kenmerkenBewerken: "✏️ Edit",
    dichtbij: "📍 Near me",
    locatieZoeken: "📍 Finding location…",
    geenLocatie: "Your browser can't determine your location.",
    locatieGeweigerd: "Your location couldn't be determined. Allow location access for this site in your browser settings.",
    jijBentHier: "You are here",
    morgen: "tomorrow",
    dag_ma: "Mon",
    dag_di: "Tue",
    dag_wo: "Wed",
    dag_do: "Thu",
    dag_vr: "Fri",
    dag_za: "Sat",
    dag_zo: "Sun",
    nuOpen: "Open now",
    tot: "until",
    gesloten: "Closed",
    opent: "opens",
    openingsuren: "Opening hours",
    urenUitleg: "E.g. 08:00-17:00, or 08:00-12:00, 13:00-18:00. Empty = closed. All empty = unknown.",
    bewaarUren: "Save hours",
    zondagVroeg: "Early Sunday",
    reviewGeven: "Write a review",
    anoniem: "Anonymous",
    reviewTekst: "What did you think? (optional)",
    reviewAanpassen: "Update review",
    reviewPlaatsen: "Post review",
    reviewVerwijderen: "Delete",
    nogGeenReviews: "No reviews yet. Be the first!",
    kiesSterren: "Choose a number of stars first.",
    zekerReview: "Delete this review?",
    barVoorstellen: "➕ Suggest a bar",
    voorstelNaam: "Name of the bar",
    voorstelWaarom: "Why is it worth it? (optional)",
    voorstelSturen: "Send suggestion",
    voorstelBedankt: "Thanks! We'll review your suggestion as soon as possible.",
    voorstellen: "Suggestions",
    geenVoorstellen: "No new suggestions.",
    overnemen: "Take over",
    weigeren: "Reject",
    zekerWeigeren: "Reject and delete this suggestion?",
    accountVerwijderen: "Delete account",
    zekerAccount: "Are you sure? Your account, favourites and reviews will be permanently deleted.",
    accountVerwijderd: "Your account has been deleted. Thanks for using Roast Route!",
    privacyLink: "Privacy policy",
    alles: "All",
    vlaanderen: "Flanders",
    antwerpen: "Antwerp",
    gent: "Ghent",
    brussel: "Brussels",
    email: "your@email.com",
    inloggen: "Log in",
    uitloggen: "Log out",
    checkMail: "Check your inbox and click the link to log in.",
    loginMislukt: "Couldn't log in:",
    privacy: "We only store your first name, email address, favourites, saved routes, newsletter choice and (if you fill it in) what you use the app for. You can unsubscribe at any time.",
    welkomTitel: "Welcome to Roast Route",
    welkomTekst: "Discover the best coffee stops, save your favourites and never miss a new bar.",
    voornaam: "First name",
    nieuwsbriefVraag: "Yes, send me a monthly email with new bars.",
    nieuwsbriefKort: "Monthly email",
    accountMaken: "Create account",
    zonderAccount: "Just have a look first",
    adres: "Street no., town",
    opslaanMislukt: "Couldn't save:",
    zekerVerwijderen: "Really delete?",
    foto: "📷 Photo",
    fotoKiezen: "Photo (optional)",
    fotoBezig: "Uploading photo…",
    zoek: "Search a stop…",
    alleTypes: "All types",
    koffie: "Specialty coffee",
    wieler: "Cycling café",
    favorieten: "★ My favourites",
    nieuweStop: "New stop",
    naam: "Name",
    beschrijving: "Short description",
    wielervriendelijk: "Cyclist-friendly",
    kiesPlek: "Enter an address and click 📍, or click on the map.",
    plekGekozen: "Spot chosen ✓",
    eerstKlikken: "Look up the address first, or click on the map!",
    toevoegen: "Add",
    stops: "stops",
    // Route plannen
    routePlannen: "🚴 Plan a route",
    jouwRoute: "Your route",
    routeUitleg: "Click the map to add points, and click a bar (or ➕ in the list) to include it. Or import your own GPX.",
    rondrit: "Loop: back to the start",
    startHier: "📍 Start here",
    gpx: "⬇️ GPX",
    googleMaps: "Google Maps",
    routeWissen: "Clear route",
    inRoute: "In route",
    naarRoute: "Add to route",
    routeBerekenen: "Calculating route…",
    routeMislukt: "The route could not be calculated. Please try again later.",
    routeStart: "Start",
    routePunt: "Point",
    aan: "at",
    barsLangsRoute: "Coffee bars within a 2 km detour",
    geenBarsLangsRoute: "No bars within a 2 km detour.",
    opDeRoute: "on your route",
    omweg: "detour",
    mijnLocatie: "My location",
    stijl_snel: "Fast",
    stijl_fietspaden: "Cycle paths",
    stijl_rustig: "Low traffic",
    routeReserve: "Simple route: the cycling route planner is unavailable right now.",
    gebruikVraag: "What do you use Roast Route for? (optional)",
    gebruik_koersen: "🚴 Cycling",
    gebruik_ontspannen: "☕ Relaxing",
    gebruik_werken: "💻 Working",
    routeDelen: "🔗 Share",
    routeBewaren: "💾 Save",
    deelTekst: "Want to ride along? Here's my route past the best coffee stops ☕🚴",
    linkGekopieerd: "Link copied! Paste it in WhatsApp, Messenger, …",
    kopieerLink: "Copy this link:",
    eerstInloggen: "Log in to save routes.",
    routeStandaardNaam: "Ride of",
    routeNaamVraag: "What do you want to call this route?",
    routeBewaard: "Route saved ✓",
    mijnRoutes: "My routes",
    routeOpenen: "Open",
    zekerRouteWissen: "Delete this route?",
    gpxImporteren: "📂 Import my GPX",
    ongedaanMaken: "↶ Undo",
    optimaliseren: "🔀 Optimise order",
    importKlik: "You're using an imported GPX. Click a bar to add it, or clear the route to plan your own.",
    gpxFout: "I can't read this GPX file. Export your route again as GPX (not FIT or TCX).",
    routeVervangen: "Replace your current route with this GPX?",
    omwegBerekenen: "Calculating detour…",
    importDelenUitleg: "An imported GPX can be saved and downloaded, but not shared via a link.",
    publiekeRoutes: "Roast Route routes",
    publicerenUitleg: "Publish: everyone can see this route",
    // Mijn profiel
    statistieken: "Statistics",
    profielfoto: "Profile photo",
    profielfotoUitleg: "Your photo appears next to your name and your reviews.",
    fotoKiezenProfiel: "📷 Choose photo",
    fotoVerwijderen: "Remove photo",
    mijnGegevens: "My details",
    voornaamLabel: "First name",
    taalLabel: "Language",
    bewaren: "Save",
    voorkeuren: "Preferences",
    voorkeurenUitleg: "The app adapts to this: your favourite region is ready when you open it, and routes suit your bike.",
    gebruikVraagKort: "What do you use Roast Route for?",
    favorieteRegio: "Favourite region",
    fietsType: "My bike",
    geenKeuze: "—",
    fiets_koersfiets: "Road bike",
    fiets_gravel: "Gravel bike",
    fiets_stadsfiets: "City bike",
    fiets_ebike: "E-bike",
    snelheidLabel: "Average speed (km/h)",
    wachtwoordWijzigen: "Change password",
    wachtwoordWijzigenKnop: "Change password",
    wachtwoordGewijzigd: "Your password has been changed ✓",
    geenNaam: "My profile",
    lidSinds: "member since",
    statFavorieten: "favourites",
    statReviews: "reviews",
    statRoutes: "routes",
    statKm: "km of routes",
    profielBewaard: "Saved ✓",
    startTitel: "Complete your profile",
    startTekst: "Just this, so Roast Route suits you right away. Everything is optional.",
    startKlaar: "Done",
    overslaan: "Skip",
    badge_eersteReview: "First review",
    badge_recensent: "Reviewer",
    badge_verzamelaar: "Collector",
    badge_planner: "Route planner",
    badge_centurion: "Centurion",
    badge_ontdekker: "Explorer",
    badgeUitleg_eersteReview: "Write your first review",
    badgeUitleg_recensent: "Write 5 reviews",
    badgeUitleg_verzamelaar: "Save 10 favourite bars",
    badgeUitleg_planner: "Save your first route",
    badgeUitleg_centurion: "Save a route of 100 km or more",
    badgeUitleg_ontdekker: "Favourites or reviews in 3 different regions",
    route: "Directions ↗",
    verwijder: "🗑️ Delete",
    fout: "Couldn't load stops.json. Are you running the app through the local server?",
    zoekOpKaart: "📍 Find on map",
    plaats: "Town",
    land: "Country",
    eerstAdres: "Enter an address first.",
    adresZoeken: "Looking up address…",
    adresGevonden: "Found! Pin not quite right? Drag it.",
    adresNietGevonden: "Address not found. Try street, number and town, or click on the map.",
  }
};

// De gekozen taal: eerst kijken wat je vorige keer koos, anders Nederlands
let taal = localStorage.getItem("taal") || "nl";

// t("zoek") geeft de tekst "zoek" terug in de gekozen taal
function t(sleutel) {
  // Ontbreekt een vertaling? Dan tonen we de Nederlandse tekst, en anders de sleutel zelf
  return teksten[taal][sleutel] ?? teksten.nl[sleutel] ?? sleutel;
}

// Zet alle teksten op de pagina in de gekozen taal
function vertaalPagina() {
  document.documentElement.lang = taal;

  // Elementen met data-t="..." krijgen de vertaalde tekst
  document.querySelectorAll("[data-t]").forEach(el => {
    el.textContent = t(el.dataset.t);
  });

  // Invulvakken met data-t-placeholder="..." krijgen een vertaalde voorbeeldtekst
  document.querySelectorAll("[data-t-placeholder]").forEach(el => {
    el.placeholder = t(el.dataset.tPlaceholder);
  });

  // De link naar de privacyverklaring: Nederlands of Engels
  document.querySelectorAll('a[data-t="privacyLink"]').forEach(link => {
    link.href = taal === "nl" ? "privacy.html" : "privacy-en.html";
  });

  // Het actieve taalknopje markeren
  document.querySelectorAll("#talen button").forEach(knop => {
    knop.classList.toggle("actief", knop.dataset.taal === taal);
  });
}

// Een andere taal kiezen (via NL / FR / EN bovenaan, of via je profiel)
function zetTaal(nieuweTaal) {
  taal = nieuweTaal;
  localStorage.setItem("taal", taal);   // onthouden voor de volgende keer
  vertaalPagina();
  teken();                              // de lijst opnieuw tekenen in de nieuwe taal
  // Ingelogd? Dan ook in je profiel bewaren (voor de mails in jouw taal)
  if (typeof gebruiker !== "undefined" && gebruiker) bewaarProfiel({ taal: taal }).catch(console.error);
}

// Klikken op NL / FR / EN
document.querySelectorAll("#talen button").forEach(knop => {
  knop.onclick = () => zetTaal(knop.dataset.taal);
});

vertaalPagina();
