// =====================================================
//  VERTALINGEN – alle teksten van de app, per taal
// =====================================================

const teksten = {
  nl: {
    tabNieuw: "Account maken",
    tabLogin: "Inloggen",
    wachtwoord: "Wachtwoord",
    wachtwoordNieuw: "Wachtwoord (min. 8 tekens)",
    vergeten: "Wachtwoord vergeten?",
    nieuwWachtwoordTitel: "Kies een nieuw wachtwoord",
    bewaarWachtwoord: "Bewaar wachtwoord",
    bevestigMail: "Bijna klaar! We stuurden je één mail om je e-mailadres te bevestigen. Daarna log je gewoon in met je wachtwoord.",
    resetVerstuurd: "Check je mailbox: we stuurden je een link om een nieuw wachtwoord te kiezen.",
    eerstEmail: "Vul eerst je e-mailadres in.",
    foutGegevens: "E-mailadres of wachtwoord klopt niet.",
    foutBevestigen: "Bevestig eerst je e-mailadres via de mail die we je stuurden.",
    foutBestaat: "Er bestaat al een account met dit e-mailadres. Log in, of kies 'Wachtwoord vergeten?'.",
    foutWachtwoord: "Kies een wachtwoord van minstens 8 tekens.",
    ondertitel: "Koffiebars en wielercafés in Vlaanderen en Brussel",
    kleur: "Kleur:",
    alleLanden: "Alle landen",
    kenmerk_laptop: "PC-friendly",
    kenmerk_wifi: "Gratis wifi",
    kenmerk_stopcontact: "Stopcontacten",
    kenmerk_rustig: "Rustig",
    kenmerkenBewerken: "✏️ Aanpassen",
    dichtbij: "📍 Dichtbij mij",
    locatieZoeken: "📍 Locatie zoeken…",
    geenLocatie: "Je browser kan je locatie niet bepalen.",
    locatieGeweigerd: "Je locatie kon niet bepaald worden. Sta locatietoegang toe voor deze site in je browserinstellingen.",
    jijBentHier: "Jij bent hier",
    morgen: "morgen",
    dag_ma: "ma",
    dag_di: "di",
    dag_wo: "wo",
    dag_do: "do",
    dag_vr: "vr",
    dag_za: "za",
    dag_zo: "zo",
    nuOpen: "Nu open",
    tot: "tot",
    gesloten: "Gesloten",
    opent: "opent",
    openingsuren: "Openingsuren",
    urenUitleg: "Bv. 08:00-17:00, of 08:00-12:00, 13:00-18:00. Leeg = gesloten. Alles leeg = onbekend.",
    bewaarUren: "Bewaar uren",
    zondagVroeg: "Zondag vroeg",
    reviewGeven: "Review geven",
    anoniem: "Anoniem",
    reviewTekst: "Wat vond je ervan? (optioneel)",
    reviewAanpassen: "Review aanpassen",
    reviewPlaatsen: "Review plaatsen",
    reviewVerwijderen: "Verwijderen",
    nogGeenReviews: "Nog geen reviews. Wees de eerste!",
    kiesSterren: "Kies eerst een aantal sterren.",
    zekerReview: "Deze review verwijderen?",
    barVoorstellen: "➕ Bar voorstellen",
    voorstelNaam: "Naam van de bar",
    voorstelWaarom: "Waarom is ze de moeite? (optioneel)",
    voorstelSturen: "Voorstel sturen",
    voorstelBedankt: "Bedankt! We bekijken je voorstel zo snel mogelijk.",
    voorstellen: "Voorstellen",
    geenVoorstellen: "Geen nieuwe voorstellen.",
    overnemen: "Overnemen",
    weigeren: "Weigeren",
    zekerWeigeren: "Dit voorstel weigeren en verwijderen?",
    accountVerwijderen: "Account verwijderen",
    zekerAccount: "Weet je het zeker? Je account, je favorieten en je reviews worden definitief verwijderd.",
    accountVerwijderd: "Je account is verwijderd. Bedankt dat je Roast Route gebruikte!",
    privacyLink: "Privacyverklaring",
    alles: "Alles",
    vlaanderen: "Vlaanderen",
    antwerpen: "Antwerpen",
    gent: "Gent",
    brussel: "Brussel",
    email: "jouw@email.be",
    inloggen: "Inloggen",
    uitloggen: "Uitloggen",
    checkMail: "Check je mailbox en klik op de link om in te loggen.",
    loginMislukt: "Inloggen lukte niet:",
    privacy: "We bewaren alleen je voornaam, je e-mailadres, je favorieten, je bewaarde routes, je nieuwsbriefkeuze en (als je het invult) waarvoor je de app gebruikt. Je kunt je altijd uitschrijven.",
    welkomTitel: "Welkom bij Roast Route",
    welkomTekst: "Ontdek de beste koffiebars, bewaar je favorieten en mis geen enkele nieuwe bar.",
    voornaam: "Voornaam",
    nieuwsbriefVraag: "Ja, stuur me maandelijks een mail met nieuwe bars.",
    nieuwsbriefKort: "Maandelijkse mail",
    accountMaken: "Account maken",
    zonderAccount: "Eerst even rondkijken",
    adres: "Straat nr, gemeente",
    opslaanMislukt: "Opslaan lukte niet:",
    zekerVerwijderen: "Zeker verwijderen?",
    foto: "📷 Foto",
    fotoKiezen: "Foto (optioneel)",
    fotoBezig: "Foto uploaden…",
    zoek: "Zoek een stop…",
    alleTypes: "Alle types",
    koffie: "Specialty koffie",
    wieler: "Wielercafé",
    favorieten: "★ Mijn favorieten",
    nieuweStop: "Nieuwe stop",
    naam: "Naam",
    beschrijving: "Korte beschrijving",
    wielervriendelijk: "Wielervriendelijk",
    kiesPlek: "Vul een adres in en klik op 📍, of klik op de kaart.",
    plekGekozen: "Plek gekozen ✓",
    eerstKlikken: "Zoek eerst het adres op, of klik op de kaart!",
    toevoegen: "Toevoegen",
    stops: "stops",
    // Route plannen
    routePlannen: "🚴 Route plannen",
    jouwRoute: "Jouw route",
    routeUitleg: "Klik op de kaart om punten toe te voegen, en op een bar (of ➕ in de lijst) om ze mee te nemen. Klik op een genummerd punt om het te verwijderen.",
    rondrit: "Rondrit: terug naar de start",
    startHier: "📍 Start bij mij",
    gpx: "⬇️ GPX",
    googleMaps: "Google Maps",
    routeWissen: "Route wissen",
    inRoute: "In route",
    naarRoute: "In route",
    routeBerekenen: "Route berekenen…",
    routeMislukt: "De route kon niet berekend worden. Probeer het straks opnieuw.",
    routeStart: "Start",
    routePunt: "Punt",
    aan: "aan",
    barsLangsRoute: "Koffiebars langs je route",
    geenBarsLangsRoute: "Geen bars binnen 2 km van je route.",
    opDeRoute: "op je route",
    omweg: "omweg",
    mijnLocatie: "Mijn locatie",
    stijl_snel: "Snel",
    stijl_fietspaden: "Fietspaden",
    stijl_rustig: "Weinig verkeer",
    routeReserve: "Eenvoudige route: de fietsrouteplanner is even niet bereikbaar.",
    gebruikVraag: "Waarvoor gebruik je Roast Route? (optioneel)",
    gebruik_koersen: "🚴 Koersen",
    gebruik_ontspannen: "☕ Ontspannen",
    gebruik_werken: "💻 Werken",
    routeDelen: "🔗 Delen",
    routeBewaren: "💾 Bewaren",
    deelTekst: "Rij je mee? Dit is mijn route langs de beste koffiestops ☕🚴",
    linkGekopieerd: "Link gekopieerd! Plak hem in WhatsApp, Messenger, …",
    kopieerLink: "Kopieer deze link:",
    eerstInloggen: "Log in om routes te bewaren.",
    routeStandaardNaam: "Rit van",
    routeNaamVraag: "Hoe wil je deze route noemen?",
    routeBewaard: "Route bewaard ✓",
    mijnRoutes: "Mijn routes",
    routeOpenen: "Openen",
    zekerRouteWissen: "Deze route verwijderen?",
    route: "Route ↗",
    verwijder: "🗑️ Verwijder",
    fout: "Kon stops.json niet laden. Start je de app via de lokale server?",
    zoekOpKaart: "📍 Zoek op kaart",
    plaats: "Gemeente",
    land: "Land",
    eerstAdres: "Vul eerst een adres in.",
    adresZoeken: "Adres zoeken…",
    adresGevonden: "Gevonden! Staat de speld niet helemaal juist? Versleep ze.",
    adresNietGevonden: "Adres niet gevonden. Probeer met straat, nummer en gemeente, of klik op de kaart.",
  },

  fr: {
    tabNieuw: "Créer un compte",
    tabLogin: "Se connecter",
    wachtwoord: "Mot de passe",
    wachtwoordNieuw: "Mot de passe (min. 8 caractères)",
    vergeten: "Mot de passe oublié ?",
    nieuwWachtwoordTitel: "Choisis un nouveau mot de passe",
    bewaarWachtwoord: "Enregistrer le mot de passe",
    bevestigMail: "Presque fini ! Nous t'avons envoyé un e-mail pour confirmer ton adresse. Ensuite, connecte-toi simplement avec ton mot de passe.",
    resetVerstuurd: "Vérifie ta boîte mail : nous t'avons envoyé un lien pour choisir un nouveau mot de passe.",
    eerstEmail: "Remplis d'abord ton adresse e-mail.",
    foutGegevens: "Adresse e-mail ou mot de passe incorrect.",
    foutBevestigen: "Confirme d'abord ton adresse via l'e-mail que nous t'avons envoyé.",
    foutBestaat: "Un compte existe déjà avec cette adresse. Connecte-toi ou choisis « Mot de passe oublié ? ».",
    foutWachtwoord: "Choisis un mot de passe d'au moins 8 caractères.",
    ondertitel: "Bars à café et cafés cyclistes en Flandre et à Bruxelles",
    kleur: "Couleur :",
    alleLanden: "Tous les pays",
    kenmerk_laptop: "PC bienvenu",
    kenmerk_wifi: "Wifi gratuit",
    kenmerk_stopcontact: "Prises",
    kenmerk_rustig: "Calme",
    kenmerkenBewerken: "✏️ Modifier",
    dichtbij: "📍 Près de moi",
    locatieZoeken: "📍 Recherche de la position…",
    geenLocatie: "Ton navigateur ne peut pas déterminer ta position.",
    locatieGeweigerd: "Impossible de déterminer ta position. Autorise l'accès à la localisation pour ce site dans les réglages du navigateur.",
    jijBentHier: "Tu es ici",
    morgen: "demain",
    dag_ma: "lun",
    dag_di: "mar",
    dag_wo: "mer",
    dag_do: "jeu",
    dag_vr: "ven",
    dag_za: "sam",
    dag_zo: "dim",
    nuOpen: "Ouvert",
    tot: "jusqu'à",
    gesloten: "Fermé",
    opent: "ouvre",
    openingsuren: "Heures d'ouverture",
    urenUitleg: "Ex. 08:00-17:00, ou 08:00-12:00, 13:00-18:00. Vide = fermé. Tout vide = inconnu.",
    bewaarUren: "Enregistrer les heures",
    zondagVroeg: "Dimanche tôt",
    reviewGeven: "Donner un avis",
    anoniem: "Anonyme",
    reviewTekst: "Qu'en as-tu pensé ? (facultatif)",
    reviewAanpassen: "Modifier l'avis",
    reviewPlaatsen: "Publier l'avis",
    reviewVerwijderen: "Supprimer",
    nogGeenReviews: "Pas encore d'avis. Sois le premier !",
    kiesSterren: "Choisis d'abord un nombre d'étoiles.",
    zekerReview: "Supprimer cet avis ?",
    barVoorstellen: "➕ Proposer un bar",
    voorstelNaam: "Nom du bar",
    voorstelWaarom: "Pourquoi vaut-il le détour ? (facultatif)",
    voorstelSturen: "Envoyer la proposition",
    voorstelBedankt: "Merci ! Nous examinerons ta proposition au plus vite.",
    voorstellen: "Propositions",
    geenVoorstellen: "Aucune nouvelle proposition.",
    overnemen: "Reprendre",
    weigeren: "Refuser",
    zekerWeigeren: "Refuser et supprimer cette proposition ?",
    accountVerwijderen: "Supprimer le compte",
    zekerAccount: "Tu es sûr ? Ton compte, tes favoris et tes avis seront définitivement supprimés.",
    accountVerwijderd: "Ton compte a été supprimé. Merci d'avoir utilisé Roast Route !",
    privacyLink: "Politique de confidentialité",
    alles: "Tout",
    vlaanderen: "Flandre",
    antwerpen: "Anvers",
    gent: "Gand",
    brussel: "Bruxelles",
    email: "ton@email.be",
    inloggen: "Se connecter",
    uitloggen: "Se déconnecter",
    checkMail: "Vérifie ta boîte mail et clique sur le lien pour te connecter.",
    loginMislukt: "Connexion impossible :",
    privacy: "Nous gardons uniquement ton prénom, ton adresse e-mail, tes favoris, tes parcours enregistrés, ton choix de newsletter et (si tu le remplis) l'usage que tu fais de l'app. Tu peux te désinscrire à tout moment.",
    welkomTitel: "Bienvenue sur Roast Route",
    welkomTekst: "Découvre les meilleurs arrêts café, garde tes favoris et ne rate aucun nouveau bar.",
    voornaam: "Prénom",
    nieuwsbriefVraag: "Oui, envoie-moi chaque mois un e-mail avec les nouveaux bars.",
    nieuwsbriefKort: "E-mail mensuel",
    accountMaken: "Créer un compte",
    zonderAccount: "D'abord jeter un œil",
    adres: "Rue n°, commune",
    opslaanMislukt: "Enregistrement impossible :",
    zekerVerwijderen: "Vraiment supprimer ?",
    foto: "📷 Photo",
    fotoKiezen: "Photo (facultatif)",
    fotoBezig: "Envoi de la photo…",
    zoek: "Chercher un arrêt…",
    alleTypes: "Tous les types",
    koffie: "Café de spécialité",
    wieler: "Café cycliste",
    favorieten: "★ Mes favoris",
    nieuweStop: "Nouvel arrêt",
    naam: "Nom",
    beschrijving: "Courte description",
    wielervriendelijk: "Adapté aux cyclistes",
    kiesPlek: "Entre une adresse et clique sur 📍, ou clique sur la carte.",
    plekGekozen: "Endroit choisi ✓",
    eerstKlikken: "Cherche d'abord l'adresse, ou clique sur la carte !",
    toevoegen: "Ajouter",
    stops: "arrêts",
    // Route plannen
    routePlannen: "🚴 Planifier un parcours",
    jouwRoute: "Ton parcours",
    routeUitleg: "Clique sur la carte pour ajouter des points, et sur un bar (ou ➕ dans la liste) pour l'inclure. Clique sur un point numéroté pour le supprimer.",
    rondrit: "Boucle : retour au départ",
    startHier: "📍 Partir d'ici",
    gpx: "⬇️ GPX",
    googleMaps: "Google Maps",
    routeWissen: "Effacer le parcours",
    inRoute: "Dans le parcours",
    naarRoute: "Au parcours",
    routeBerekenen: "Calcul du parcours…",
    routeMislukt: "Impossible de calculer le parcours. Réessaie plus tard.",
    routeStart: "Départ",
    routePunt: "Point",
    aan: "à",
    barsLangsRoute: "Cafés le long de ton parcours",
    geenBarsLangsRoute: "Aucun café à moins de 2 km de ton parcours.",
    opDeRoute: "sur ton parcours",
    omweg: "de détour",
    mijnLocatie: "Ma position",
    stijl_snel: "Rapide",
    stijl_fietspaden: "Pistes cyclables",
    stijl_rustig: "Peu de trafic",
    routeReserve: "Parcours simple : le planificateur vélo est momentanément indisponible.",
    gebruikVraag: "Pourquoi utilises-tu Roast Route ? (facultatif)",
    gebruik_koersen: "🚴 Vélo",
    gebruik_ontspannen: "☕ Détente",
    gebruik_werken: "💻 Travail",
    routeDelen: "🔗 Partager",
    routeBewaren: "💾 Enregistrer",
    deelTekst: "Tu viens rouler ? Voici mon parcours par les meilleurs cafés ☕🚴",
    linkGekopieerd: "Lien copié ! Colle-le dans WhatsApp, Messenger, …",
    kopieerLink: "Copie ce lien :",
    eerstInloggen: "Connecte-toi pour enregistrer des parcours.",
    routeStandaardNaam: "Sortie de",
    routeNaamVraag: "Quel nom pour ce parcours ?",
    routeBewaard: "Parcours enregistré ✓",
    mijnRoutes: "Mes parcours",
    routeOpenen: "Ouvrir",
    zekerRouteWissen: "Supprimer ce parcours ?",
    route: "Itinéraire ↗",
    verwijder: "🗑️ Supprimer",
    fout: "Impossible de charger stops.json. L'app tourne-t-elle via le serveur local ?",
    zoekOpKaart: "📍 Chercher sur la carte",
    plaats: "Commune",
    land: "Pays",
    eerstAdres: "Entre d'abord une adresse.",
    adresZoeken: "Recherche de l'adresse…",
    adresGevonden: "Trouvé ! L'épingle n'est pas tout à fait au bon endroit ? Déplace-la.",
    adresNietGevonden: "Adresse introuvable. Essaie avec rue, numéro et commune, ou clique sur la carte.",
  },

  en: {
    tabNieuw: "Create account",
    tabLogin: "Log in",
    wachtwoord: "Password",
    wachtwoordNieuw: "Password (min. 8 characters)",
    vergeten: "Forgot your password?",
    nieuwWachtwoordTitel: "Choose a new password",
    bewaarWachtwoord: "Save password",
    bevestigMail: "Almost there! We sent you one email to confirm your address. After that, just log in with your password.",
    resetVerstuurd: "Check your inbox: we sent you a link to choose a new password.",
    eerstEmail: "Fill in your email address first.",
    foutGegevens: "Email address or password is incorrect.",
    foutBevestigen: "Please confirm your email address first, using the email we sent you.",
    foutBestaat: "An account with this email already exists. Log in, or choose 'Forgot your password?'.",
    foutWachtwoord: "Choose a password of at least 8 characters.",
    ondertitel: "Coffee bars and cycling cafés in Flanders and Brussels",
    kleur: "Colour:",
    alleLanden: "All countries",
    kenmerk_laptop: "PC-friendly",
    kenmerk_wifi: "Free wifi",
    kenmerk_stopcontact: "Power outlets",
    kenmerk_rustig: "Quiet",
    kenmerkenBewerken: "✏️ Edit",
    dichtbij: "📍 Near me",
    locatieZoeken: "📍 Finding location…",
    geenLocatie: "Your browser can't determine your location.",
    locatieGeweigerd: "Your location couldn't be determined. Allow location access for this site in your browser settings.",
    jijBentHier: "You are here",
    morgen: "tomorrow",
    dag_ma: "Mon",
    dag_di: "Tue",
    dag_wo: "Wed",
    dag_do: "Thu",
    dag_vr: "Fri",
    dag_za: "Sat",
    dag_zo: "Sun",
    nuOpen: "Open now",
    tot: "until",
    gesloten: "Closed",
    opent: "opens",
    openingsuren: "Opening hours",
    urenUitleg: "E.g. 08:00-17:00, or 08:00-12:00, 13:00-18:00. Empty = closed. All empty = unknown.",
    bewaarUren: "Save hours",
    zondagVroeg: "Early Sunday",
    reviewGeven: "Write a review",
    anoniem: "Anonymous",
    reviewTekst: "What did you think? (optional)",
    reviewAanpassen: "Update review",
    reviewPlaatsen: "Post review",
    reviewVerwijderen: "Delete",
    nogGeenReviews: "No reviews yet. Be the first!",
    kiesSterren: "Choose a number of stars first.",
    zekerReview: "Delete this review?",
    barVoorstellen: "➕ Suggest a bar",
    voorstelNaam: "Name of the bar",
    voorstelWaarom: "Why is it worth it? (optional)",
    voorstelSturen: "Send suggestion",
    voorstelBedankt: "Thanks! We'll review your suggestion as soon as possible.",
    voorstellen: "Suggestions",
    geenVoorstellen: "No new suggestions.",
    overnemen: "Take over",
    weigeren: "Reject",
    zekerWeigeren: "Reject and delete this suggestion?",
    accountVerwijderen: "Delete account",
    zekerAccount: "Are you sure? Your account, favourites and reviews will be permanently deleted.",
    accountVerwijderd: "Your account has been deleted. Thanks for using Roast Route!",
    privacyLink: "Privacy policy",
    alles: "All",
    vlaanderen: "Flanders",
    antwerpen: "Antwerp",
    gent: "Ghent",
    brussel: "Brussels",
    email: "your@email.com",
    inloggen: "Log in",
    uitloggen: "Log out",
    checkMail: "Check your inbox and click the link to log in.",
    loginMislukt: "Couldn't log in:",
    privacy: "We only store your first name, email address, favourites, saved routes, newsletter choice and (if you fill it in) what you use the app for. You can unsubscribe at any time.",
    welkomTitel: "Welcome to Roast Route",
    welkomTekst: "Discover the best coffee stops, save your favourites and never miss a new bar.",
    voornaam: "First name",
    nieuwsbriefVraag: "Yes, send me a monthly email with new bars.",
    nieuwsbriefKort: "Monthly email",
    accountMaken: "Create account",
    zonderAccount: "Just have a look first",
    adres: "Street no., town",
    opslaanMislukt: "Couldn't save:",
    zekerVerwijderen: "Really delete?",
    foto: "📷 Photo",
    fotoKiezen: "Photo (optional)",
    fotoBezig: "Uploading photo…",
    zoek: "Search a stop…",
    alleTypes: "All types",
    koffie: "Specialty coffee",
    wieler: "Cycling café",
    favorieten: "★ My favourites",
    nieuweStop: "New stop",
    naam: "Name",
    beschrijving: "Short description",
    wielervriendelijk: "Cyclist-friendly",
    kiesPlek: "Enter an address and click 📍, or click on the map.",
    plekGekozen: "Spot chosen ✓",
    eerstKlikken: "Look up the address first, or click on the map!",
    toevoegen: "Add",
    stops: "stops",
    // Route plannen
    routePlannen: "🚴 Plan a route",
    jouwRoute: "Your route",
    routeUitleg: "Click the map to add points, and click a bar (or ➕ in the list) to include it. Click a numbered point to remove it.",
    rondrit: "Loop: back to the start",
    startHier: "📍 Start here",
    gpx: "⬇️ GPX",
    googleMaps: "Google Maps",
    routeWissen: "Clear route",
    inRoute: "In route",
    naarRoute: "Add to route",
    routeBerekenen: "Calculating route…",
    routeMislukt: "The route could not be calculated. Please try again later.",
    routeStart: "Start",
    routePunt: "Point",
    aan: "at",
    barsLangsRoute: "Coffee bars along your route",
    geenBarsLangsRoute: "No bars within 2 km of your route.",
    opDeRoute: "on your route",
    omweg: "detour",
    mijnLocatie: "My location",
    stijl_snel: "Fast",
    stijl_fietspaden: "Cycle paths",
    stijl_rustig: "Low traffic",
    routeReserve: "Simple route: the cycling route planner is unavailable right now.",
    gebruikVraag: "What do you use Roast Route for? (optional)",
    gebruik_koersen: "🚴 Cycling",
    gebruik_ontspannen: "☕ Relaxing",
    gebruik_werken: "💻 Working",
    routeDelen: "🔗 Share",
    routeBewaren: "💾 Save",
    deelTekst: "Want to ride along? Here's my route past the best coffee stops ☕🚴",
    linkGekopieerd: "Link copied! Paste it in WhatsApp, Messenger, …",
    kopieerLink: "Copy this link:",
    eerstInloggen: "Log in to save routes.",
    routeStandaardNaam: "Ride of",
    routeNaamVraag: "What do you want to call this route?",
    routeBewaard: "Route saved ✓",
    mijnRoutes: "My routes",
    routeOpenen: "Open",
    zekerRouteWissen: "Delete this route?",
    route: "Directions ↗",
    verwijder: "🗑️ Delete",
    fout: "Couldn't load stops.json. Are you running the app through the local server?",
    zoekOpKaart: "📍 Find on map",
    plaats: "Town",
    land: "Country",
    eerstAdres: "Enter an address first.",
    adresZoeken: "Looking up address…",
    adresGevonden: "Found! Pin not quite right? Drag it.",
    adresNietGevonden: "Address not found. Try street, number and town, or click on the map.",
  }
};

// De gekozen taal: eerst kijken wat je vorige keer koos, anders Nederlands
let taal = localStorage.getItem("taal") || "nl";

// t("zoek") geeft de tekst "zoek" terug in de gekozen taal
function t(sleutel) {
  // Ontbreekt een vertaling? Dan tonen we de Nederlandse tekst, en anders de sleutel zelf
  return teksten[taal][sleutel] ?? teksten.nl[sleutel] ?? sleutel;
}

// Zet alle teksten op de pagina in de gekozen taal
function vertaalPagina() {
  document.documentElement.lang = taal;

  // Elementen met data-t="..." krijgen de vertaalde tekst
  document.querySelectorAll("[data-t]").forEach(el => {
    el.textContent = t(el.dataset.t);
  });

  // Invulvakken met data-t-placeholder="..." krijgen een vertaalde voorbeeldtekst
  document.querySelectorAll("[data-t-placeholder]").forEach(el => {
    el.placeholder = t(el.dataset.tPlaceholder);
  });

  // De link naar de privacyverklaring: Nederlands of Engels
  document.querySelectorAll('a[data-t="privacyLink"]').forEach(link => {
    link.href = taal === "nl" ? "privacy.html" : "privacy-en.html";
  });

  // Het actieve taalknopje markeren
  document.querySelectorAll("#talen button").forEach(knop => {
    knop.classList.toggle("actief", knop.dataset.taal === taal);
  });
}

// Klikken op NL / FR / EN
document.querySelectorAll("#talen button").forEach(knop => {
  knop.onclick = () => {
    taal = knop.dataset.taal;
    localStorage.setItem("taal", taal);   // onthouden voor de volgende keer
    vertaalPagina();
    teken();                              // de lijst opnieuw tekenen in de nieuwe taal
  };
});

vertaalPagina();
